name: Update Version and README

on:
  push:
    branches:
      - master

jobs:
  update_version_and_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Determine current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Read merge counter from file
        id: read_counter
        run: echo "::set-output name=counter::$(cat counter.txt || echo '0')"

      - name: Determine if this is a merge commit
        id: is_merge_commit
        run: |
          if git show --format=%P -s | grep -q " "; then
            echo "::set-output name=is_merge::true"
          else
            echo "::set-output name=is_merge::false"
          fi

      - name: Increment merge counter
        if: steps.is_merge_commit.outputs.is_merge == 'true'
        id: increment_counter
        run: |
          counter=$((${{ steps.read_counter.outputs.counter }} + 1))
          echo "::set-output name=counter::$counter"
        
      - name: Update version file with date and merge counter
        run: echo "3.0.0.${{ steps.current_date.outputs.date }}.${{ steps.increment_counter.outputs.counter }}" > VERSION.txt

      - name: Update README.md
        run: |
          sed -i "s/Current Version:.*/Current Version: 3.0.0.${{ steps.current_date.outputs.date }}.${{ steps.increment_counter.outputs.counter }} (This line will be automatically updated to reflect the latest version)/" README.md

      - name: Set up Git identity
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit version and README update
        run: |
          git add VERSION.txt README.md
          git commit -m "Update version to 3.0.0.${{ steps.current_date.outputs.date }}.${{ steps.increment_counter.outputs.counter }}"
          git push
