name: Update Version and README

on:
  push:
    branches:
      - main

jobs:
  update_version_and_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Determine current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Read merge counter from file
        id: read_counter
        run: echo "::set-output name=counter::$(cat counter.txt || echo '0')"

      - name: Increment merge counter
        id: increment_counter
        run: echo "::set-output name=counter::${{ steps.read_counter.outputs.counter + 1 }}"

      - name: Update version file with date and merge counter
        run: echo "3.0.0.${{ steps.current_date.outputs.date }}.${{ steps.increment_counter.outputs.counter }}" > VERSION.txt

      - name: Update README.md
        run: sed -i "s/Current Version: .*/Current Version: 3.0.0.${{ steps.current_date.outputs.date }}.${{ steps.increment_counter.outputs.counter }}/" README.md

      - name: Commit version and README update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION.txt README.md
          git commit -m "Update version to 3.0.0.${{ steps.current_date.outputs.date }}.${{ steps.increment_counter.outputs.counter }}"
          git push
