name: Daily Versioning

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  push:
    branches:
      - master

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Calculate new version
        id: new-version
        run: |
          VERSION_PREFIX="3.0.0"
          DATE=$(date +'%Y%m%d')
          echo "NEW_VERSION=${VERSION_PREFIX}.${DATE}" >> $GITHUB_ENV

      - name: Update version in project
        run: |
          # Example: Update version in a properties file or specific project files
          # Replace with your project's version file path and mechanism
          echo "Version=${{ env.NEW_VERSION }}" > version.txt

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update version to ${{ env.NEW_VERSION }}" || exit 0 
          git push
